### ISSUE TITLE
Django 1.4, 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by embedded1** [joshuakarjala/django-hunger#67]
I'm running Django 1.4.8 and the bundled six version (1.2.0) does not contain the PY2 attribute.
It has PY3 and else for PY2.

Could you please fix this issue for older Django versions?

**Comment by yesimon** [comment]
Currently only supporting Django>=1.5. Feel free to submit a pull request for 1.4 support since it is still a LTS release, but be aware that 1.8 is around the corner as the new LTS.

**Comment by embedded1** [comment]
ok, i'm about to launch next week so I guess I will be using 1.4 for a
while..
pull request is on its way
